name: Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman Graph
        uses: ghaction-pacman-contribution-graph/ghaction-pacman-contribution-graph@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: techyshubham18
          output_dir: pacman-output
          
      - name: Push to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pacman-output
          publish_branch: pacman-output
